spring.application.name=ohgnoy
server.port=8087

spring.config.import=optional:classpath:application-db.properties,optional:classpath:application-secret.properties

# Swagger / springdoc
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true

# Email SMTP 설정 (Naver)
spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=${EMAIL}
spring.mail.password=${PW}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.naver.com